package com.company.tracker.controller;

public enum ResponseType {
    CREDENTIALS_STUDENTS,
    ADDED,
    BACK,
    EXIT,
    HELP,
    INCORRECT,
    UNDEFINED,
    GENERAL_STAT,
    INCORRECT_FIRST_NAME,
    INCORRECT_SECOND_NAME,
    INCORRECT_LAST_NAME,
    INCORRECT_EMAIL,
    NO_STUDENTS_BY_ID,
    POINTS_UPDATED,
    EMAIL_ALREADY_TAKEN,
    SHOW_STATS,
    NO_STUDENTS_FOUND,
    UnknownCourse,
    INCORRECT_POINTS_FORMAT,
    TABLE_HEADER,
    TABLE_CONTENT,
    RECIPIENT_STUDENT,
    SENDER,
    EMAIL_TEXT,
    NOTIFIED_COUNT;

}
